twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/Resources/views/RuleCrud': RuleCrud
        '%kernel.project_dir%/src/Resources/views/Rule': Rule

when@test:
    twig:
        strict_variables: true
